/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct T {
    pub x: ::std::os::raw::c_int,
    pub y: ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of T"][::std::mem::size_of::<T>() - 8usize];
    ["Alignment of T"][::std::mem::align_of::<T>() - 4usize];
    ["Offset of field: T::x"][::std::mem::offset_of!(T, x) - 0usize];
    ["Offset of field: T::y"][::std::mem::offset_of!(T, y) - 4usize];
};
extern "C" {
    pub fn get_value() -> T;
}
extern "C" {
    pub fn print_value(t: T);
}
